### ISSUE TITLE
java.util.concurrent.CancellationException

### ISSUE THREAD

**Issue by gokejnr** [matthiasn/BirdWatch#27] opened 2014-12-11 19:33 UTC
Hi Matthias,

First, thanks a LOT for your work on this. Second and to the issue, it looks like I'm running into concurrency issues with the Clojure version of BirdWatch on my VPS. Here's what I see-

`#<CancellationException java.util.concurrent.CancellationException>`

And shortly after, 

`Exception while processing chunk #<Exception java.lang.Exception: JSON error (unexpected character): c>`

I'm assuming the second error is as a result of the first, perhaps chunks are not being processed properly because the chunks don't make it in completely due to the concurrency error. Although, this is just a hypothesis. Any idea why this would be the case?

Thanks a lot.

**Comment by matthiasn** [comment] 2015-01-21 00:52
Will close this for now because I cannot reproduce it. Feel free to reopen the issue anytime when you have additional information. Thanks!

**Closed by matthiasn** 2015-01-21 00:52 UTC
